version: '3'

services:
  seidel:
    build:
      context: .
      args:
        - IMAGE_NAME=${IMAGE_NAME}
        - IMAGE_VERSION=${IMAGE_VERSION}
    image: lycantropos/seidel:0.0.2-alpha
    volumes:
      - ./seidel/:/opt/seidel/seidel/
      - ./src/:/opt/seidel/src/
      - ./tests/:/opt/seidel/tests/
      - ./README.md:/opt/seidel/README.md
      - ./requirements.txt:/opt/seidel/requirements.txt
      - ./requirements-tests.txt:/opt/seidel/requirements-tests.txt
      - ./setup.py:/opt/seidel/setup.py
      - ./pytest.ini:/opt/seidel/pytest.ini
    entrypoint: pytest
